version: '3.5'
# Use this script for running up nightfall_3 client in 'developer' mode with local
# bindings.  See the readme for more information.
services:
  client_1:
    image: ghcr.io/eyblockchain/nightfall3-client:latest
    volumes:
      - type: volume
        source: build_client_1
        target: /app/build
    networks:
      - nightfall_network
    ports:
      - 8090:80
    depends_on:
      - worker_1
      - mongodb_client_1
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-localhost}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      LOG_HTTP_PAYLOAD_ENABLED: ${LOG_HTTP_PAYLOAD_ENABLED:-true}
      LOG_HTTP_FULL_DATA: ${LOG_HTTP_FULL_DATA:-false}
      BLOCKCHAIN_WS_HOST: ${BLOCKCHAIN_WS_HOST:-blockchain}
      BLOCKCHAIN_PORT: ${BLOCKCHAIN_PORT:-8546}
      CIRCOM_WORKER_HOST: worker_1
      MONGO_URL: ${CLIENT_MONGO_URL:-mongodb://mongodb_client_1}
      CONTRACT_FILES_URL: ${CONTRACT_FILES_URL}
      LAUNCH_LOCAL: 1
      GAS_ESTIMATE_ENDPOINT: ${GAS_ESTIMATE_ENDPOINT}
    command: ['npm', 'run', 'dev']

  mongodb_client_1:
    image: mongo:4.4.1-bionic
    hostname: mongodb_client_1
    ports:
      - 27018:27017
    networks:
      - nightfall_network
    command: --quiet
    volumes:
      - type: volume
        source: mongodb_client_1
        target: /data/db

  worker_1:
    image: ghcr.io/eyblockchain/nightfall3-worker:latest
    volumes:
      - type: volume
        source: proving_files_client_1
        target: /app/output/
    networks:
      - nightfall_network
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      LOG_HTTP_PAYLOAD_ENABLED: ${LOG_HTTP_PAYLOAD_ENABLED:-true}
      LOG_HTTP_FULL_DATA: ${LOG_HTTP_FULL_DATA:-false}
      CIRCUIT_FILES_URL: ${CIRCUIT_FILES_URL}

  client-txw_1:
    build:
      dockerfile: docker/client_txw.Dockerfile
      context: ..
    image: client-txw:latest
    volumes:
      - type: volume
        source: build_client_1
        target: /app/build
    networks:
      - nightfall_network
    ports:
      - 3010:80
    depends_on:
      - mongodb_client_1
    environment:
      AUTHENTICATION_KEY: ${AUTHENTICATION_KEY}
      AUTOSTART_RETRIES: ${AUTOSTART_RETRIES:-600}
      BLOCKCHAIN_URL: ${BLOCKCHAIN_URL}
      BLOCKCHAIN_WS_HOST: ${BLOCKCHAIN_WS_HOST:-blockchain}
      BLOCKCHAIN_PORT: ${BLOCKCHAIN_PORT:-8546}
      CIRCOM_WORKER_HOST: ${CIRCOM_WORKER_HOST:-worker}
      ENDPOINTS_WHITELISTED: ${ENDPOINTS_WHITELISTED}
      ENABLE_QUEUE: ${ENABLE_QUEUE:-1}
      ENVIRONMENT: ${ENVIRONMENT:-localhost}
      ETH_ADDRESS: ${ETH_ADDRESS}
      ETH_PRIVATE_KEY: ${ETH_PRIVATE_KEY}
      ETH_NETWORK: ${ETH_NETWORK}
      GAS_ESTIMATE_ENDPOINT: ${GAS_ESTIMATE_ENDPOINT}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      LOG_HTTP_PAYLOAD_ENABLED: ${LOG_HTTP_PAYLOAD_ENABLED:-true}
      LOG_HTTP_FULL_DATA: ${LOG_HTTP_FULL_DATA:-false}
      MONGO_URL: ${CLIENT_MONGO_URL:-mongodb://mongodb:27017}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-amqp://rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      OPTIMIST_HOST: ${OPTIMIST_HOST:-optimist}
      OPTIMIST_PORT: ${OPTIMIST_PORT:-80}
      STATE_GENESIS_BLOCK: ${STATE_GENESIS_BLOCK:-0}
      USE_EXTERNAL_NODE: ${USE_EXTERNAL_NODE}
      CLIENT_TX_WORKER_COUNT: ${CLIENT_TX_WORKER_COUNT:-2}
      CLIENT_URL: ${CLIENT_URL:-http://client}
      PERFORMANCE_BENCHMARK_ENABLE: ${PERFORMANCE_BENCHMARK_ENABLE:-false}
    command: ['npm', 'run', 'start-tx-worker']

  client-bpw_1:
    build:
      dockerfile: docker/client_bwp.Dockerfile
      context: ..
    image: client-bpw:latest
    volumes:
      - type: volume
        source: build
        target: /app/build
    networks:
      - nightfall_network
    ports:
      - 3020:80
    depends_on:
      - mongodb
    environment:
      AUTHENTICATION_KEY: ${AUTHENTICATION_KEY}
      AUTOSTART_RETRIES: ${AUTOSTART_RETRIES:-600}
      BLOCKCHAIN_URL: ${BLOCKCHAIN_URL}
      BLOCKCHAIN_WS_HOST: ${BLOCKCHAIN_WS_HOST:-blockchain}
      BLOCKCHAIN_PORT: ${BLOCKCHAIN_PORT:-8546}
      CIRCOM_WORKER_HOST: ${CIRCOM_WORKER_HOST:-worker}
      ENDPOINTS_WHITELISTED: ${ENDPOINTS_WHITELISTED}
      ENABLE_QUEUE: ${ENABLE_QUEUE:-1}
      ENVIRONMENT: ${ENVIRONMENT:-localhost}
      ETH_ADDRESS: ${ETH_ADDRESS}
      ETH_PRIVATE_KEY: ${ETH_PRIVATE_KEY}
      ETH_NETWORK: ${ETH_NETWORK}
      GAS_ESTIMATE_ENDPOINT: ${GAS_ESTIMATE_ENDPOINT}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      LOG_HTTP_PAYLOAD_ENABLED: ${LOG_HTTP_PAYLOAD_ENABLED:-true}
      LOG_HTTP_FULL_DATA: ${LOG_HTTP_FULL_DATA:-false}
      MONGO_URL: ${CLIENT_MONGO_URL:-mongodb://mongodb:27017}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-amqp://rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      OPTIMIST_HOST: ${OPTIMIST_HOST:-optimist}
      OPTIMIST_PORT: ${OPTIMIST_PORT:-80}
      STATE_GENESIS_BLOCK: ${STATE_GENESIS_BLOCK:-0}
      USE_EXTERNAL_NODE: ${USE_EXTERNAL_NODE}
      PERFORMANCE_BENCHMARK_ENABLE: ${PERFORMANCE_BENCHMARK_ENABLE:-false}
    command: ['npm', 'run', 'start-bp-worker']

volumes:
  mongodb_client_1:
  proving_files_client_1:
  build_client_1:

networks:
  nightfall_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
